.PHONY: test lint tag check-git-clean pull-eva-base eva eva-base upload-eva upload-eva-base doc publish-doc all

all: test lint doc

release: doc publish-doc eva upload-eva

test:
	nosetests

lint:
	flake8 eva/ --ignore=E501,E265

tag:
	git tag --sign --message "Version $(shell python setup.py --version)" $(shell python setup.py --version)

check-git-clean:
	ifeq ($(shell test "`git status --porcelain | wc -l`" != "0"; echo $$?), 1)
		$(error Please clean up your working directory and push your changes before building EVA)
	endfi

pull-eva-base:
	docker pull metno/eva-base

eva: test lint pull-eva-base
	docker build --no-cache --tag metno/eva:$(shell python setup.py --version) docker/eva
	docker tag metno/eva:$(shell python setup.py --version) metno/eva:$(shell python setup.py --version | cut -d. -f1-2)
	docker tag metno/eva:$(shell python setup.py --version) metno/eva:$(shell python setup.py --version | cut -d. -f1)

eva-base:
	docker build --no-cache --tag metno/eva-base docker/eva-base

upload-eva:
	docker push metno/eva:$(shell python setup.py --version)
	docker push metno/eva:$(shell python setup.py --version | cut -d. -f1-2)
	docker push metno/eva:$(shell python setup.py --version | cut -d. -f1)

upload-eva-base:
	docker push metno/eva-base

doc:
	cd doc && $(MAKE) html

publish-doc: doc
	cd doc/_build/html && git add -A && git commit -a -m "Documentation auto-generated by Sphinx" && git push
